### ISSUE TITLE
Computer AI

### ISSUE THREAD

**Issue by EyalBrilling** [orbarilan4/SuperPong#23]
one of the players will be controlled by the computer.
3 levels- easy,medium and hard.
will implement by giving the ai the ability to know where the ball will hit on his side,which he will move to, to hit the ball.
to not make the computer perfect,after some amount of time,there is a chance for the computer to go to the wrong way for some time,with a cool down.this is based on on level difficulty.different timers need to be tested to decide what feels right and natural for the gameplay.

**Comment by guyshoham** [comment]
I think that an easy implementation will be that the computer will move right if the ball is on the right side of his pad, and move left if the ball is on the left side of the pad.

The difficulty will be the speed, so Hard AI will be faster than EASY AI

**Comment by orbarilan4** [comment]
Keep it for the last
