### ISSUE TITLE
PowerUp

### ISSUE THREAD

**Issue by EyalBrilling** [orbarilan4/SuperPong#26]
create and show one random type of a power up in a random place on the playground,some seconds after the last one got taken.
when a power up gets taken the player who hit it gets it.(will determinate which player took it based on ball vector) and the power up gets destroyed.
kind of power ups:
faster paddle,opponent slower paddle...

**Comment by EyalBrilling** [comment]
completed random spawning on playground

**Comment by guyshoham** [comment]
Good power up tutorial: 
https://www.youtube.com/watch?v=CLSiRf_OrBk
