### ISSUE TITLE
Game instructions and keyboard settings scene

### ISSUE THREAD

**Issue by orbarilan4** [orbarilan4/SuperPong#31]
Plus, we should add an option to get this screen by the menu.

**Comment by orbarilan4** [comment]
Redefine or reset settings - does not needed

**Comment by guyshoham** [comment]
the UI Texts position are very tricky. we need to learn more about it

**Comment by guyshoham** [comment]
Controls Menu is on when clicking **'H'** while in game.
Also, I added pause/resume functions for pausing the game when the user is in controls menu
